version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: > 
      cohortextractor:latest generate_cohort 
      --study-definition study_definition 
      --index-date-range "2020-03-01 to 2020-06-01 by month" 
      --output-dir=output
      --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input*.csv
        
  analysis_in_r:
    run: > 
      r:latest analysis/join_outputs.R 
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        joined_csv: output/input_joined.csv
      moderately_sensitive:
        session_info: output/session_info.txt
